const productos = [
  {
    id: 1,
    nombre: "BGH SILENT AIR",
    precio: 72000,
    stock: 10,
    tipo: "AIRE VENTANA",
    imagen: "../img/aireVentana.jpg",
  },
  {
    id: 2,
    nombre: "BGH TURBO AIR",
    precio: 102000,
    stock: 10,
    tipo: "AIRE SPLIT",
    imagen: "../img/bghSplit.jpg",
  },
  {
    id: 3,
    nombre: "SURREY XCOLD",
    precio: 120000,
    stock: 10,
    tipo: "AIRE VENTANA",
    imagen: "../img/aireVentana.jpg",
  },
  {
    id: 4,
    nombre: "NEX FREE AIR",
    precio: 89000,
    stock: 10,
    tipo: "AIRE VENTANA",
    imagen: "../img/aireVentana.jpg",
  },
  {
    id: 5,
    nombre: "SANSEI INVERTER",
    precio: 132000,
    stock: 10,
    tipo: "AIRE SPLIT",
    imagen: "../img/sanseiSplit.jpg",
  },
  {
    id: 6,
    nombre: "PHILCO 2881",
    precio: 96000,
    stock: 10,
    tipo: "AIRE SPLIT",
    imagen: "../img/sanseiSplit.jpg",
  },
  {
    id: 7,
    nombre: "TCL ELITE",
    precio: 93000,
    stock: 10,
    tipo: "AIRE SPLIT",
    imagen: "../img/sanseiSplit.jpg",
  },
  {
    id: 8,
    nombre: "LILIANA VP16P",
    precio: 12600,
    stock: 10,
    tipo: "VENTILADOR PIE",
    imagen: "../img/ventiladorPie.jpg",
  },
  {
    id: 9,
    nombre: "INDELPLAS IV16",
    precio: 7200,
    stock: 10,
    tipo: "VENTILADOR PIE",
    imagen: "../img/ventiladorPie.jpg",
  },
  {
    id: 10,
    nombre: "PEABODY PE-VTR42",
    precio: 31800,
    stock: 10,
    tipo: "VENTILADOR TECHO",
    imagen: "../img/ventiladoTecho.jpg",
  },
  {
    id: 11,
    nombre: "KANJI KJH-FH1209",
    precio: 10900,
    stock: 10,
    tipo: "VENTILADOR 3 EN 1",
    imagen: "../img/ventilador3en1.jpg",
  },
  {
    id: 12,
    nombre: "AXEL AX-VTPOTAR",
    precio: 25900,
    stock: 10,
    tipo: "VENTILADOR TECHO",
    imagen: "../img/ventiladoTecho.jpg",
  },
  {
    id: 13,
    nombre: "LILIANA VW2016",
    precio: 17300,
    stock: 10,
    tipo: "VENTILADOR DE PARED",
    imagen: "../img/ventiladorPared.jpg",
  },
  {
    id: 14,
    nombre: "LILIANA CALOVENTOR",
    precio: 2500,
    stock: 10,
    tipo: "CALOVENTOR",
    imagen: "../img/caloventorPortatilLiliana.jpg",
  },
  {
    id: 15,
    nombre: "ESTUFA ELECTRICA CUARZO",
    precio: 4000,
    stock: 10,
    tipo: "ESTUFA",
    imagen: "../img/estufaElectrica.jpg",
  },
  {
    id: 16,
    nombre: "ESTUFA A GAS EMEGE",
    precio: 15000,
    stock: 10,
    tipo: "ESTUFA",
    imagen: "../img/estufaGas.jpg",
  },
  {
    id: 17,
    nombre: "CALOVENTOR DE PARED DREMTEAM",
    precio: 12000,
    stock: 10,
    tipo: "CALOVENTOR",
    imagen: "../img/caloventorPared.jpg",
  },
  {
    id: 18,
    nombre: "ESTUFA ELECTRICA 3 VELAS",
    precio: 9000,
    stock: 10,
    tipo: "ESTUFA",
    imagen: "../img/estufaElectrica.jpg",
  },
  {
    id: 19,
    nombre: "ESTUFA ELECTRICA 3 VELAS NUEVA",
    precio: 9000,
    stock: 10,
    tipo: "ESTUFA",
    imagen: "../img/estufaElectricaNueva.jpg",
  },
  {
    id: 20,
    nombre: "CALOVENTOR PARED CON CONTROL",
    precio: 10000,
    stock: 10,
    tipo: "CALOVENTOR",
    imagen: "../img/caloventorParedControl.jpg",
  },
  {
    id: 21,
    nombre: "CALOVENTOR PIE",
    precio: 2000,
    stock: 10,
    tipo: "CALOVENTOR",
    imagen: "../img/caloventorPortatil.jpg",
  },
  {
    id: 22,
    nombre: "ESTUFA A GAS EMEGE EURO",
    precio: 12000,
    stock: 10,
    tipo: "ESTUFA",
    imagen: "../img/estufaGas.jpg",
  },
];

export default productos;
